/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lojaoriodopeixe.vg.calc.pis.cofins.view;

import br.com.lojaoriodopeixe.vg.calc.pis.cofins.calculator.Calculator;
import br.com.lojaoriodopeixe.vg.calc.pis.cofins.utils.Utils;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vagner
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        util.centerWindow(this);
        this.setAlwaysOnTop(true);
        util.nextFieldWithEnter(this);
    }

    Utils util = new Utils();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstValue = new javax.swing.JTextField();
        ThirdValue = new javax.swing.JTextField();
        SecondValue = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TotalViewer = new javax.swing.JTextField();
        PisViewer = new javax.swing.JTextField();
        CofinsViewer = new javax.swing.JTextField();
        getCalc = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora PIS/COFINS v0.9");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Valor 1");

        jLabel2.setText("Valor 2");

        jLabel3.setText("Valor 3");

        FirstValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstValueActionPerformed(evt);
            }
        });

        jLabel4.setText("PIS");

        jLabel5.setText("CONFINS");

        jLabel6.setText("TOTAL");

        TotalViewer.setEditable(false);
        TotalViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalViewerActionPerformed(evt);
            }
        });

        PisViewer.setEditable(false);

        CofinsViewer.setEditable(false);

        getCalc.setText("Calcular");
        getCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCalcActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PisViewer)
                    .addComponent(CofinsViewer)
                    .addComponent(TotalViewer))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(FirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThirdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(getCalc)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(FirstValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThirdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getCalc)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TotalViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PisViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CofinsViewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        setBounds(0, 0, 400, 268);
    }// </editor-fold>//GEN-END:initComponents

    private void FirstValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstValueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FirstValue.setText("");
        SecondValue.setText("");
        ThirdValue.setText("");
        TotalViewer.setText("");
        TotalViewer.setBackground(Color.decode("-986896"));
        PisViewer.setText("");
        PisViewer.setBackground(Color.decode("-986896"));
        CofinsViewer.setText("");
        CofinsViewer.setBackground(Color.decode("-986896"));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void getCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCalcActionPerformed

        if (!FirstValue.getText().isEmpty() || !SecondValue.getText().isEmpty() || !ThirdValue.getText().isEmpty()) {
            BigDecimal stringFirstValue;
            BigDecimal stringSecondValue;
            BigDecimal stringThirdValue;
            List<BigDecimal> values = new ArrayList<BigDecimal>();
            try {
                if (!FirstValue.getText().isEmpty()) {
                    stringFirstValue = new BigDecimal(FirstValue.getText().replace(",", "."));
                    values.add(stringFirstValue);
                }
                if (!SecondValue.getText().isEmpty()) {
                    stringSecondValue = new BigDecimal(SecondValue.getText().replace(",", "."));
                    values.add(stringSecondValue);
                }
                if (!ThirdValue.getText().isEmpty()) {
                    stringThirdValue = new BigDecimal(ThirdValue.getText().replace(",", "."));
                    values.add(stringThirdValue);
                }

                Calculator c = new Calculator();
                String total = c.getTotalValue(values).toPlainString();
                String totalPis = c.getPIS(c.getTotalValue(values)).toPlainString();
                String totalConfins = c.getCONFINS(c.getTotalValue(values)).toPlainString();

                TotalViewer.setText("R$ " + total.replace(".", ","));
                TotalViewer.setForeground(Color.WHITE);
                TotalViewer.setBackground(Color.decode("101211"));
                PisViewer.setText("R$ " + totalPis.replace(".", ","));
                PisViewer.setBackground(Color.RED);
                PisViewer.setForeground(Color.WHITE);
                CofinsViewer.setText("R$ " + totalConfins.replace(".", ","));
                CofinsViewer.setBackground(Color.BLUE);
                CofinsViewer.setForeground(Color.WHITE);
            } catch (NumberFormatException nfe) {
                this.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(null, "Atenção! Valor inválido informado!");
                TotalViewer.setText("");
                PisViewer.setText("");
                CofinsViewer.setText("");
                this.setAlwaysOnTop(true);
            }
        } else {
            this.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(null, "É preciso haver pelo menos um valor!");
            this.setAlwaysOnTop(true);
        }

    }//GEN-LAST:event_getCalcActionPerformed

    private void TotalViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalViewerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalViewerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CofinsViewer;
    private javax.swing.JTextField FirstValue;
    private javax.swing.JTextField PisViewer;
    private javax.swing.JTextField SecondValue;
    private javax.swing.JTextField ThirdValue;
    private javax.swing.JTextField TotalViewer;
    private javax.swing.JButton getCalc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
